### ISSUE TITLE
Templates: Update the BOM template

### ISSUE THREAD

**Issue by andrempmattos** [spacelab-ufsc/pcb-standard#17]
- Add the footprint column

**Comment by YanAzer** [comment]
This issue was solved via 7c4bab7e74d0d3dafde5beaa6ba220a24536b0ec, new column parameters were added as showed in the imagem below:
![image](https://user-images.githubusercontent.com/40373964/95003385-27ce8f00-05b5-11eb-9f4c-2e98b2b0b7f2.png)
@andrempmattos @mgm8
